[variables]
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_INSTALL_CMD = "rm -rf /app/node_modules/.cache || true && PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium npm ci --production=false"
NIXPACKS_BUILD_CMD = "npm run build"

[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[start]
cmd = "npm start"
