[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium"]

[phases.install]
cmds = [
  "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium npm ci --production=false"
]

[start]
cmd = "npm start"
